# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-26 23:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movie',
            options={'ordering': ['-release'], 'verbose_name': 'filme', 'verbose_name_plural': 'filmes'},
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='realease',
            new_name='release',
        ),
    ]
